app/app/urls.py
from django.urls import path, include
from django.conf import settings 
from django.conf.urls.static import static

from drf_yasg import openapi
from drf_yasg.views import get_schema_view as swagger_get_schema_view

schema_view = swagger_get_schema_view(
    openapi.Info(
        title="Employee API",
        default_version='1.0.0',
        description='API documentation description'
    ),
    public=True
)

urlpatterns = [
    path('api/v1/',
         include([
             path('swagger/schema/', schema_view.with_ui('swagger', cache_timeout=0), name="swagger-schema"),
             path('images/', include(('images.urls', 'images')))
         ])),
    path('auth/', include(('users.urls', 'users'), namespace='auth')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/images/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from . import viewsets

router = SimpleRouter()
router.register(r'', viewsets.ImageViewset, basename='image')


urlpatterns = router.get_urls()

app/leaves/api/urls.py
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from . import viewsets

router = SimpleRouter()
router.register(r'', viewsets.LeaveViewset, basename='leave')


urlpatterns = router.get_urls()

app/users/urls.py
from django.contrib import admin
from django.urls import path

from . import views

urlpatterns = [
    path('signup/', views.sign_up_view, name='signup'),
    path('signin/', views.sign_in_view, name='signin'),
    path('signout/', views.sign_out_view, name='signout'),
]

app/core/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db.models.signals import post_save
from django.db.models import Sum
from django.utils.translation import gettext_lazy as _

class UserManager(BaseUserManager):

    def create_user(self, email, password=None, **extra_fields):
        """Creates and saves a new user"""
        if not email:
            raise ValueError('Users must have email address')
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        """Creates and saves a new super user"""
        user = self.create_user(email, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """Custom user model that supports using email instead username"""
    email = models.EmailField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=True)

    objects = UserManager()

    USERNAME_FIELD = 'email'


def upload_to(instance, filename):
    return 'collectedImages/{filename}'.format(filename=filename)


class BaseImageModel(models.Model):
    class Meta:
        abstract = True

    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    image = models.ImageField(_("Image"), upload_to=upload_to, default='collectedImages/no_name300x300.jpg')
    width = models.FloatField(name='width', default=0)
    height = models.FloatField(name='height', default=0)
    url = models.CharField(max_length=255)
    alt = models.CharField(max_length=255)


    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        return super(BaseImageModel, self).save(*args, **kwargs)


class Image(BaseImageModel):
    pass

app/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from core.models import User
from django.contrib.auth import authenticate

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=255, help_text='Required. Provide a valid email address.')
    name = forms.CharField(max_length=255, help_text='Required. Provide a name.')

    class Meta:
        model = User
        fields = ('email', 'name', 'password1', 'password2', )

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password1')
        return super(SignUpForm, self).clean() 
        
class SignInForm (forms.Form):
    email = forms.EmailField(max_length=100, label='Email')
    password = forms.CharField(max_length=100, label='Password', widget = forms.PasswordInput)

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if email and len(password) < 5:
            user = authenticate(email = email, password = password)
            if not user:
                raise forms.ValidationError('Credentials is not correct!')
        return super(SignInForm, self).clean() 

app/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from . import forms

def sign_up_view(request):
    if request.method == 'POST':
        form = forms.SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password1')
            login(request, authenticate(email=email, password=password))
            return redirect('base:leaves')
        else:
            pass
    else:
        form = forms.SignUpForm()

    return render(request, 'users/signup.html', {'form':form})

def sign_in_view(request):
    if request.method == 'POST':
        form = forms.SignInForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            try:
                login(request, authenticate(email=email, password=password))
                return redirect('base:leaves')
            except AttributeError:
                messages.error(request, 'User does not exist.')
        else:
            messages.error(request,'Please provide valid information.')
    else:
        form = forms.SignInForm()
    return render(request, 'users/signin.html', {'form':form})



def sign_out_view(request):
    logout(request)
    return redirect('auth:signin')   

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Employee Attendance Management</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
  <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <link rel="stylesheet" href="{% static 'css/bootstrap-datetimepicker.min.css' %}">
  <script src="https://kit.fontawesome.com/a8d18a1bf5.js" crossorigin="anonymous"></script>
</head>
<body class="bg-gradient-primary">
    {% block content %}
    {% endblock %}
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/jquery.easing.min.js' %}"></script>
  <script src="{% static 'js/moment.min.js' %}"></script>
  <script src="{% static 'js/bootstrap-datetimepicker.min.js' %}"></script>
  <script src="{% static 'js/base.min.js' %}"></script>
  <script src="{% static 'js/leaves.js' %}"></script>
  <script src="{% static 'js/ajax-calls.js' %}"></script>
</body>

app/templates/leaves/archive_leaves.html
{% extends 'base.html' %}
{% block content %}
  <div id="wrapper">
    {% include 'leaves/sidebar.html' %}
    <div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
            {% include 'leaves/topbar.html'%}
            <div class="content">
                <div class="animated fadeIn">
                    <div class="orders">
                            <div class="col-xl-12">
                                    <h4 class="box-title my-4 color-black">Leaves Archive</h4>
                                        <div class="table-stats order-table ov-h">
                                            <table class="table seperate">
                                                <thead >
                                                    <tr>
                                                        <th class="color-black">Leave Type</th>
                                                        <th class="color-black">Date</th>
                                                        <th class="color-black">Time</th>
                                                        <th class="color-black">Status</th>
                                                        <th></th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                    <tr id="new-attend" class="card-row">
                                                           
                                                      </tr>
                                                    
                                                    {% for al in archived_leaves %}
                                                    <tr class="card-row">
                                                            <td>  <span class="name">{{al.leave_type}}</span> </td>
                                                            <td> <span class="product">{{al.leave_start_date|date:"Y-m-d"}} - {{al.leave_end_date|date:"Y-m-d"}}</span> </td>
                                                            <td><span>{{al.leave_start_time|time:"H:i A"}} - {{al.leave_end_time|time:"H:i A"}}</span></td>
                                                            <td>
                                                                <span class="badge badge-waiting">{{al.status}}</span>
                                                            </td>
                                                            <td>
                                                           <a class="btn btn-danger ml-2 btn-circle btn-sm" data-toggle="modal" data-target="#deleteModal" href="#"><i class="fas fa-trash"></i></a></td>
                                                        </tr>
                                                        <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                                          <div class="modal-dialog" role="document">
                                                            <div class="modal-content">
                                                              <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">Are you sure you want to do this?</h5>
                                                                <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                                                  <span aria-hidden="true">×</span>
                                                                </button>
                                                              </div>
                                                              <div class="modal-body">This action is irreversible.</div>
                                                              <div class="modal-footer">
                                                                <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                                                                <a class="btn btn-danger" href="{% url 'base:delete_archive_leave' al.id %}">Delete</a>
                                                              </div>
                                                            </div>
                                                          </div>
                                                        </div>
                                                        {% endfor %}
                                                </tbody>
                                            </table>
                                            {% if not archived_leaves %}
                                                <div class="alert text-center fade show" role="alert">
                                                    No archived leaves yet
                                                  </div>
                                            {% endif %}
                                        </div> 
                            </div> 
                        </div>
                    </div>
    
          </div>
    </div>
  </div>
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
{% endblock %}

app/templates/leaves/sidebar.html
 {% block content %}
 <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
      <div class="sidebar-brand-icon rotate-n-15">
        <i class="fas fa-space-shuttle"></i>
      </div>
      <div class="sidebar-brand-text mx-3">EAM</div>
    </a>
    <hr class="sidebar-divider my-0">
    <li class="nav-item">
      <a class="nav-link" href="index.html">
        <i class="fas fa-fw fa-tachometer-alt"></i>
        <span>Dashboard</span></a>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
      Modules
    </div>
    <li class="nav-item {% url 'base:leaves' as leaves %} {% url 'base:archive_leaves' as archive_leaves %} {% if request.path == leaves or request.path == archive_leaves %} active {% endif %}">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
        <i class="fas fa-calendar-check"></i>
        <span>Leaves</span>
      </a>
      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">Leaves</h6>
          <a class="collapse-item {% url 'base:leaves' as leaves %} {% if request.path == leaves %} active {% endif %}" href="{% url 'base:leaves' %}">Leaves Dashboard</a>
          <a class="collapse-item {% url 'base:archive_leaves' as archive_leaves %} {% if request.path == archive_leaves %} active {% endif %}" href="{% url 'base:archive_leaves'%}">Archive</a>
        </div>
      </div>
    </li>
    <hr class="sidebar-divider">
    <div class="sidebar-heading">
      User Settings
    </div>
    <li class="nav-item">
      <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
        <i class="fas fa-user-cog"></i>
        <span>Settings</span>
      </a>
      <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
        <div class="bg-white py-2 collapse-inner rounded">
          <h6 class="collapse-header">User Settings</h6>
          <a class="collapse-item" href="#">My Profile</a>
          <a class="collapse-item" href="#">Staff Section</a>
      </div>
    </li>
    <div class="sidebar-heading">
      Manager
    </div>
    {% if request.user.is_staff %}
    <li class="nav-item {% url 'base:manager_leaves' as manager_leaves %} {% if request.path == manager_leaves %} active {% endif %}">
      <a class="nav-link" href="{% url 'base:manager_leaves' %}">
        <i class="fas fa-table"></i>
        <span>Leave Manager</span></a>
    </li>
    {% endif %}
    <hr class="sidebar-divider d-none d-md-block">
    <div class="text-center d-none d-md-inline">
      <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>
  </ul>
{% endblock %}

app/templates/leaves/topbar.html
{% block content %}
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
      <i class="fa fa-bars"></i>
    </button>
<ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{user.name}}</span>
        {% if profilepic.image %} 
        <img class="img-profile rounded-circle" src="{{profilepic.image.url}}">
        {% else %}
        <div class="img-profile rounded-circle" style="background-color: #132f81;">
          <p style="text-align: center; color: white; font-size: 14px; margin:3px; font-weight: bold;">{{user.name|slice:'1'}}</p>
        </div>
        {% endif %}

        
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <div class="dropdown-divider"></div>
        <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          Logout
        </a>
      </div>
    </li>
  </ul>
</nav>
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <a class="btn btn-primary" href="{% url 'auth:signout' %}">Logout</a>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/manager/manager_leave_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div id="wrapper">
    {% include 'leaves/sidebar.html' %}
    <div id="content-wrapper" class="d-flex flex-column">
      <div id="content">
            {% include 'leaves/topbar.html'%}
            <div class="content">
                <div class="animated fadeIn">
                    <div class="row">
                <div class="col-lg-7">
                    <div class="card shadow mb-4">
                      <div class="card-body">
                          <div class="row">
                              <div class="col-sm-4 py-4">
                                <div class="text-center my-4">
                                  {% if profilepic.image %}
                                    <img src="{{profilepic.image.url}}" alt="Profile Image" class="mx-auto rounded-circle img-fluid" width="145rem">
                                    {% else %}
                                    <div class="circle">
                                      <p style="text-align: center; color: white; font-size: 92px; font-weight: bold; position: relative; top: 76px;">{{user.name|slice:'1'}}</p>
                                    {% endif %}
                                </div>
                            
                                </div>
                            </div>
                                <div class="col-sm-8 py-4">
                                  <ul class="list-unstyled font-small mb-0 leave-details-list">
                                    <li>
                                    <p class="text-uppercase mb-2"><strong>Employee</strong></p>
                                    <p class="text-muted mb-4">{{leave.user.name}}</p>
                                    </li>
        
                                    <li>
                                        <p class="text-uppercase mb-2"><strong>Leave Type</strong></p>
                                        <p class="text-muted mb-4">{{leave.leave_type}}</p>
                                    </li>
        
                                    <li>
                                    <p class="text-uppercase mb-2"><strong>Leave Dates</strong></p>
                                    <p class="text-muted mb-4">{{leave.leave_start_date}}-{{leave.leave_end_date}}</p>
                                    </li>
        
                                    <li>
                                    <p class="text-uppercase mb-2"><strong>Leave Time</strong></p>
                                    <p class="text-muted mb-4">{{leave.leave_start_time}}-{{leave.leave_end_time}}</p>
                                    </li>
        
                                    <li>
                                    <p class="text-uppercase mb-2"><strong>Status</strong></p>
                                    <p class="text-muted mb-4">{{leave.status}}</p>
                                    </li>
        
                                    <li>
                                        <p class="text-uppercase mb-2"><strong>Reason</strong></p>
                                        <p class="text-muted mb-4">{{leave.leave_reason}}</p>
                                    </li>
        
                                    
                                </ul>
                                </div>
                                </div>
                      </div>
                    </div>
                  </div>
      
                  <!-- Pie Chart -->
                  <div class="col-lg-5">
                    <div class="card">
                      <div class="card-body pb-3">
                      <div class="chart-pie mr-3 py-3">
                        <canvas id="myPieChart"></canvas>
                      </div>
                      <div class="text-center small">
                        <span class="mr-2">
                          <i class="fas fa-circle indicator-available"></i> Availabe
                        </span>
                        <span class="mr-2">
                          <i class="fas fa-circle indicator-approved"></i> Approved
                        </span>
                        <span class="mr-2">
                          <i class="fas fa-circle indicator-waiting"></i> Waiting
                        </span>
                      </div>
                    </div>
                  </div>
                  </div>
                </div>
                    </div>
                </div>
          </div>
    </div>
  </div>
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
  <script src="{% static 'js/Chart.min.js' %}"></script>
  <script>
    // Set new default font family and font color to mimic Bootstrap's default styling
Chart.defaults.global.defaultFontFamily = 'Segoe UI';
Chart.defaults.global.defaultFontColor = '#858796';

// Pie Chart Example
var ctx = document.getElementById("myPieChart");
var myPieChart = new Chart(ctx, {
  type: 'doughnut',
  data: {
    labels: ["Waiting","Approved","Available Leave Days"],
    datasets: [{
      data: ["{{waiting}}","{{approved}}","{{available_leave_limit}}"],
      backgroundColor: ['#6e6967','#00c292','#FECA1B'],
      hoverBackgroundColor: ['#6e6967','#00c292','#FECA1B'],
      hoverBorderColor: "rgba(234, 236, 244, 1)",
    }],
  },
  options: {
    maintainAspectRatio: false,
    tooltips: {
      backgroundColor: "rgb(255,255,255)",
      bodyFontColor: "#858796",
      borderColor: '#dddfeb',
      borderWidth: 1,
      xPadding: 15,
      yPadding: 15,
      displayColors: false,
      caretPadding: 10,
    },
    legend: {
      display: false
    },
    cutoutPercentage: 80,
  },
});

</script>
{% endblock %}

app/templates/users/signin.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-xl-6 col-md-9">
        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <div class="row">
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
                    <h1 class="h4 text-gray-900 mb-4">Sign In</h1>
                  </div>
                  <form class="user" method="POST">
                      {% csrf_token %}
                    <div class="form-group">
                      <input type="text" name="email" class="form-control form-control-user" placeholder="Email">
                    </div>
                    <div class="form-group">
                      <input type="password" name="password" class="form-control form-control-user" placeholder="Password">
                    </div>
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                     Sign In
                    </button>

                  </form>
                  {% if messages %}
                  <hr>
                    {% for message in messages %}

                  <div class="alert {{ message.tags }}">
                      {{ message }}
                  </div>
                    {% endfor %}
                  {% endif %}
                  
                  <hr>
                  <div class="text-center">
                    <a class="small" href="#">Forgot Password?</a>
                  </div>
                  <div class="text-center">
                    <a class="small" href="{% url 'auth:signup' %}">Create an Account!</a>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

app/templates/users/signup.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xl-6 col-md-9">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <div class="row">
          <div class="col-lg-12">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form class="user" method="post">
                  {% csrf_token %}
                <div class="form-group row">
                  <div class="col-sm-12 mb-3 mb-sm-0">
                    <input type="email"  name="email" class="form-control form-control-user" placeholder="Email">
                  </div>
                </div>
                <div class="form-group">
                  <input type="text" name="name" class="form-control form-control-user" placeholder="Full Name">
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="password"  name="password1" class="form-control form-control-user" placeholder="Password">
                  </div>
                  <div class="col-sm-6">
                    <input type="password"  name="password2" class="form-control form-control-user" placeholder="Confirm Password">
                  </div>
                </div>
                <button type="submit" class="btn btn-primary btn-user btn-block">
                  Sign Up
                </button>
              </form>
                {% for field in form %}
                {% for error in field.errors %}
                <div class="alert alert-danger mt-2">
                  {{ error }}
              </div>
                {% endfor %}            
                {% endfor %}
              <hr>
              <div class="text-center">
                <a class="small" href="#">Forgot Password?</a>
              </div>
              <div class="text-center">
                <a class="small" href="{% url 'auth:signin' %}">Already have an account? Sign in!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
    </div>
</div>
{% endblock%}